name: "Coverage"

on:
    pull_request:
    workflow_dispatch:

    push:
        branches: [ "*" ]

    schedule:
        -   cron: "0 8 * * 1"

jobs:
    coverage:
        name: "Phpunit"
        uses: contributte/.github/.github/workflows/phpunit-coverage.yml@master
        with:
            php: "8.2"
            make: "init coverage"
