name: "Phpunit"

on:
    pull_request:
    workflow_dispatch:

    push:
        branches: [ "*" ]

    schedule:
        -   cron: "0 8 * * 1"

jobs:
    test83:
        name: "Phpunit"
        uses: contributte/.github/.github/workflows/phpunit.yml@master
        with:
            php: "8.3"
            make: "init tests"

    test82:
        name: "Phpunit"
        uses: contributte/.github/.github/workflows/phpunit.yml@master
        with:
            php: "8.2"
            make: "init tests"
